export const AGREGAR_COMPONENTE = 'AGREGAR_COMPONENTE';
export const AGREGAR_COMPONENTE_EXITO = 'AGREGAR_COMPONENTE_EXITO';
export const AGREGAR_COMPONENTE_ERROR = 'AGREGAR_COMPONENTE_ERROR'; 

export const COMENZAR_DESCARGA_COMPONENTES = 'COMENZAR_DESCARGA_COMPONENTES';
export const DESCARGA_COMPONENTES_EXITO = 'DESCARGA_COMPONENTES_EXITO';
export const DESCARGA_COMPONENTES_ERROR = 'DESCARGA_COMPONENTES_ERROR';

